### ISSUE TITLE
Multiline not parsed 

### ISSUE THREAD

**Issue by forstjiri** [ava007/wnk_translation#4]
When you add multiple lines to the textarea, it doesnt get parsed like it should:

```
msgid "V pořádku obnoveno"
msgstr "line 1"
"line 2"
```

Instead it looks like this:
```

```
msgid "V pořádku obnoveno"
msgstr "line 1
line 2"
```
which is invalid

**Comment by ava007** [comment]
implemented 
see https://github.com/ava007/wnk_translation/commit/22d9a62a28bafdb21ef04c7cb4e3942ee9a67a0e
